### ISSUE TITLE
Error while executing Chart

### ISSUE THREAD

**Issue by pantou** [flatangle/flatlib#51]
In windows 7 whether in Spyder or cmd when I run Chart I get the following errors
chart = Chart(date, pos)
Traceback (most recent call last):

  File "<ipython-input-7-7d0f3f548143>", line 1, in <module>
    chart = Chart(date, pos)

  File "C:\ProgramData\Anaconda3\lib\site-packages\flatlib\chart.py", line 53, in __init__
    self.objects = ephem.getObjectList(IDs, date, pos)

  File "C:\ProgramData\Anaconda3\lib\site-packages\flatlib\ephem\ephem.py", line 34, in getObjectList
    objList = [getObject(ID, date, pos) for ID in IDs]

  File "C:\ProgramData\Anaconda3\lib\site-packages\flatlib\ephem\ephem.py", line 34, in <listcomp>
    objList = [getObject(ID, date, pos) for ID in IDs]

  File "C:\ProgramData\Anaconda3\lib\site-packages\flatlib\ephem\ephem.py", line 29, in getObject
    obj = eph.getObject(ID, date.jd, pos.lat, pos.lon)

  File "C:\ProgramData\Anaconda3\lib\site-packages\flatlib\ephem\eph.py", line 48, in getObject
    obj = swe.sweObject(ID, jd)

  File "C:\ProgramData\Anaconda3\lib\site-packages\flatlib\ephem\swe.py", line 71, in sweObject
    'lonspeed': sweList[3],

IndexError: tuple index out of range

Any suggestion to solve the problem?

**Comment by joaoventura** [comment]
Please look into other issues before opening a new one. This has already been solved at #41!
