### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by minhtl1982** [flatangle/flatlib#56]
```
date = Datetime('1986/01/30', '00:20', '+00:00')
pos = GeoPos('105e51', '21n02')
chart = Chart(date, pos)
sun = chart.get(const.SUN)
print(sun)
```

And I got error below:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    chart = Chart(date, pos)
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/chart.py", line 53, in __init__
    self.objects = ephem.getObjectList(IDs, date, pos)
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/ephem/ephem.py", line 35, in getObjectList
    objList = [getObject(ID, date, pos) for ID in IDs]
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/ephem/ephem.py", line 35, in <listcomp>
    objList = [getObject(ID, date, pos) for ID in IDs]
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/ephem/ephem.py", line 30, in getObject
    obj = eph.getObject(ID, date.jd, pos.lat, pos.lon)
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/ephem/eph.py", line 35, in getObject
    pflon = tools.pfLon(jd, lat, lon)
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/ephem/tools.py", line 33, in pfLon
    if isDiurnal(jd, lat, lon):
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/ephem/tools.py", line 51, in isDiurnal
    return utils.isAboveHorizon(ra, decl, mcRA, lat)
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/utils.py", line 39, in isAboveHorizon
    dArc, _ = dnarcs(decl, lat)
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/utils.py", line 23, in dnarcs
    dArc = 180 + 2 * ascdiff(decl, lat)
  File "/home/minhtl3/chiemtinh/chiemtinh/flatlib/utils.py", line 18, in ascdiff
    ad = math.asin(math.tan(delta) * math.tan(phi))
ValueError: math domain error

```

Do you guys have any ideas?
Thanks,

**Comment by joaoventura** [comment]
The parameters for building a chart is LAT / LONG. You switched them..
It should be `pos = GeoPos('21n02', '105e51')`
and NOT `GeoPos('105e51', '21n02')`..
